### ISSUE TITLE
JavaScript DOM Manipulation – Full Course for Beginners

### ISSUE THREAD

**Issue by fastmarketo** [john-smilga/react-jobs-app#1]
You have onc eourse on youTube where are its HTML files, CSS files? Are they here on repository?

**Comment by john-smilga** [comment]
I'm sorry but I don't understand which project you are talking about.

**Comment by fastmarketo** [comment]
Dear Sir, This one → 

1. https://www.youtube.com/watch?v=YDkB4xpP6Sc
2. https://www.youtube.com/watch?v=m_HJ3juuFvo

**Comment by john-smilga** [comment]
But it has nothing to do with repo 🤦‍♂️
It's in the video description, just look for source files
